title: "Ciara Palfreyman "
description: A website with a blog
footer_text: Copyright 2021 Ciara Palfreyman
header_feature_image: ../uploads/65761187-0bcf-4ff6-b2de-f4c432d50878-stratford-upon-avon.jpg
header_text: Ciara Rachel
header_text_color: "#eeb4ff"
bannerheight: 100vh
logo: ../uploads/fullsizeoutput_1e5d.jpeg
favicon: ../uploads/585839a54f6ae202fedf27cb.png
gridlayout: false
fixednavbar: false
upzoom: true
