title: "Ciara Palfreyman "
description: A website with a blog
footer_text: Copyright 2021 Ciara Palfreyman
header_feature_image: ../uploads/placeholder4.jpg
header_text: Ciara Rachel
header_text_color: "#000000"
bannerheight: 100vh
logo: ../uploads/ppp.jpeg
favicon: ../uploads/world.png
gridlayout: false
fixednavbar: false
upzoom: true
