title: Ciara Palfreyman recipes
description: A website with a blog
footer_text: Copyright 2021 Ciara Palfreyman
header_feature_image: ../uploads/placeholder1.jpg
header_text: Oxford Dreams
header_text_color: "#eeb4ff"
bannerheight: 100vh
logo: ../uploads/placeholder4.jpg
favicon: ../uploads/moussaka.jpg
gridlayout: false
fixednavbar: false
upzoom: true
