title: "Ciara Palfreyman "
description: A website with a blog
footer_text: Copyright 2021 Ciara Palfreyman
header_feature_image: ../uploads/grt-watermelon-fruit-pizza-1296x728-header.jpg
header_text: Ciara Rachel
header_text_color: "#eeb4ff"
bannerheight: 100vh
logo: ../uploads/img_0280.jpg
favicon: ../uploads/585839a54f6ae202fedf27cb.png
gridlayout: false
fixednavbar: false
upzoom: true
